# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new build to the Google Play Store internal test track"
  lane :internal do
    gradle(task: "clean bundleGmsRelease")
    upload_to_play_store(
      track: 'internal',
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Submit a new build to the Google Play Store beta track"
  lane :beta do
    gradle(task: "clean bundleGmsRelease")
    upload_to_play_store(
      track: 'beta',
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean bundleGmsRelease")
    upload_to_play_store(
      rollout: "0.2",
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
