name: Build

on:
  push:
    branches-ignore:
      - create-pull-request/update-oui
      - "dependabot/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - uses: burrunan/gradle-cache-action@v1
        name: Build and test project
        with:
          arguments: |
            build
            test
