name: Build

on:
  push:
    branches-ignore: "dependabot/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: ./gradlew build