name: Update bundled OUIs

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 15 * *'

jobs:
  update-oui:
    runs-on: ubuntu-latest
    steps:
      - name: Set date
        shell: bash
        run: echo "DATE=$(date -I)" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python requirements
        run: pip install requests

      - name: Run update script
        run: python update_oui.py

      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run unit tests
        run: ./gradlew test

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: Update bundled OUIs @ ${{ env.DATE }}
          title: Update bundled OUIs @ ${{ env.DATE }}
          branch: create-pull-request/update-oui
          delete-branch: true
