name: Update bundled OUIs

on:
  schedule:
    - cron:  '0 1 15 * *'

jobs:
  update-oui:
    runs-on: ubuntu-latest
    steps:
      - name: Set date
        shell: bash
        run: echo "DATE=$(date -I)" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python requirements
        run: pip install requests

      - name: Run update script
        run: python update_oui.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          # Using a Personal Access Token will allow the "build" workflow to be triggered by the pull request
          # https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-537478081
          token: ${{ secrets.PULL_REQUEST_TOKEN }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: Update bundled OUIs @ ${{ env.DATE }}
          title: Update bundled OUIs @ ${{ env.DATE }}
          branch: create-pull-request/update-oui
          delete-branch: true
